name: PlayerAuto
main: LamPocketVN\PlayerAuto\PlayerAuto
version: 0.3
api: 4.0.0

permissions:
  playerauto.autosell:
    default: true
  playerauto.autofix:
    default: true
  playerauto.autofeed:
    default: true
