name: PlayerAuto
main: LamPocketVN\PlayerAuto\PlayerAuto
version: 0.2.0.lpk
api: 3.9.0

permissions:
  playerauto.autosell:
    default: true
    description: "Allow player use command /autosell"
  playerauto.autofix:
    default: true
  playerauto.autofeed:
    default: true